"""create executions table

Revision ID: 95495c18531e
Revises: 
Create Date: 2026-04-15 20:17:28.559542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95495c18531e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('api_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_picked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_stored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('cpu_time_ms', sa.Integer(), nullable=True),
    sa.Column('wall_time_ms', sa.Integer(), nullable=True),
    sa.Column('fail_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executions')
    # ### end Alembic commands ###
