services:
  api:
    container_name: onpyrunner-api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    command: ["uvicorn", "onpyrunner_api.app:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - ljweel-dev-network


  worker:
    networks:
      - ljweel-dev-network
    privileged: true
    stop_grace_period: 1s
    cgroup: host
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    command: ["python", "-m", "onpyrunner_worker.main"]
    deploy:
      resources:
        limits:
          cpus: 1.2


  redis:
    image: redis:7
    networks:
      - ljweel-dev-network

  db:
    image: postgres:16-alpine
    networks:
      - ljweel-dev-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  ljweel-dev-network:
    external: true
    name: ljweel-dev-network
